export const UPDATE_CONNECTION_STATUS = 'UPDATE_CONNECTION_STATUS';
export const UPDATE_PAGE_STATUS = 'UPDATE_PAGE_STATUS';
export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
